// Generated by android-icons/scripts/generate-icon-packs.mjs. Do not edit.
import CoreGraphics

/// Map symbols from the common pack. Selection is always explicit.
public enum CommonMapIcons {
    /// Hospital or medical facility.
    public static let hospital = MapIconGlyph(
        id: "hospital",
        commands: [
            .moveTo(CGPoint(x: 9, y: 3)),
            .lineTo(CGPoint(x: 15, y: 3)),
            .lineTo(CGPoint(x: 15, y: 9)),
            .lineTo(CGPoint(x: 21, y: 9)),
            .lineTo(CGPoint(x: 21, y: 15)),
            .lineTo(CGPoint(x: 15, y: 15)),
            .lineTo(CGPoint(x: 15, y: 21)),
            .lineTo(CGPoint(x: 9, y: 21)),
            .lineTo(CGPoint(x: 9, y: 15)),
            .lineTo(CGPoint(x: 3, y: 15)),
            .lineTo(CGPoint(x: 3, y: 9)),
            .lineTo(CGPoint(x: 9, y: 9)),
            .close,
        ]
    )
}
